<a href="https://colab.research.google.com/github/vikash2006-dot/Python/blob/main/Day6_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dct={
    'name':['Tom','Jerry','Krish','Jack'],
    'age':[20,21,22,23],
    'roll':[1,2,3,4]
}

df= pd.DataFrame(dct);
# print(df)
df
# display function print data with proper format
display(df)

df = pd.DataFrame(dct,index=['a','b','c','d'])
display(df)

    name  age  roll
0    Tom   20     1
1  Jerry   21     2
2  Krish   22     3
3   Jack   23     4

    name  age  roll
a    Tom   20     1
b  Jerry   21     2
c  Krish   22     3
d   Jack   23     4

In [ ]:
# gives the whole data of the file
df= pd.read_csv('student_data.csv')
#print (df)

# gives first 5 data of the data
df.head(5)
# gives the last 5 data of the data
df.tail(5)
# gives the size of the data in the terms of rows and columns
df.shape

# gives the meta data of the data i.e. data about the data
df.info()

# describes the data in briefly
# here 25% is q1, 50% is q2, 75% is q3 , here q is called Quartile
# q2 is median of the data , q1 is the median of starting to q2 ,q3 is the median from q2 to end of the data
df.describe()

# gives column
df.columns
# index
df.index

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
# to excess the specific column of the data
df[['study_hours','internet_usage']]

# to excess the row of the data , this gives row in column format
df.iloc[0:5]

# to filter the data according to study_hours
df.loc[df['study_hours']==11]
# to filter the data according to study_hours , but it gives only two columns study_hours and sleep_hours
df.loc[df['study_hours']==11,['study_hours','sleep_hours']]

df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8]

#
df2= df.loc[df['study_hours']==11]
df2[['study_hours','sleep_hours']]

df.loc[df['assignments_completed']==8].iloc[1]

# loc and iloc works on rows but to excess column we use this syntax
df[df['assignments_completed']>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
import pandas as pd

df=pd.read_csv("student_data.csv")
# This adds the new column to the data
df['age']= 20;

# column rename , this returns new dataframe
df = df.rename(columns ={'assignments_completed':'assign_completed'})
df
# This replace the coulmn with previous column in data
df = df.rename(columns ={'assignments_completed':'assign_completed'},inplace=True)
df
# Remove rows and columns
df.drop('assign_completed', axis=1)
display(df)

In [ ]:
dct1={
    'name': 'Nikhil',
    'study':'Full',
    'lovelife':'None',
    'Bachhodi':'puri',
    'sleep':'kumbhkarn'

}
# Remove misisng value : removes NULL values
dct1.dropna()
display(dct1)


# Sort values by column
df.sort_values()

AttributeError: 'dict' object has no attribute 'dropna'